### ISSUE TITLE
Environment too strict

### ISSUE THREAD

**Issue by jscheid** [stephanbuys/docker-compose-types#15]
Hi, docker-compose handles values other than string in `environment` (as a map), including boolean and number. For example, `docker compose run test` with the file below prints `true` and `1234` without any complaints:

```yml
version: "3.4"

services:
  test:
    image: busybox
    environment:
      foo: true
      bar: 1234
    command: sh -c 'echo $$foo && echo $$bar'
```

Tested with Docker version 20.10.17
