### ISSUE TITLE
`extends: some-daemon` notation fails

### ISSUE THREAD

**Issue by snaggen** [stephanbuys/docker-compose-types#41]
```yaml
  some-other-daemon:
    extends: some-daemon
    image: docker.io/good-repo:latest
```
This is a valid notation for extends, and you can even interpret https://docs.docker.com/compose/multiple-compose-files/extends/#extending-services-within-the-same-file  that it is the preferred notation unless you are extending from another file. 

But using that notation fails, with docker-compose-types expecting a map, not a string.
